### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside 

### ISSUE THREAD

**Issue by popotang** [danielstjules/jsinspect#58]
```shell
class Inspector extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jsinspect/bin/jsinspect:9:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```
NodeJS version : v5.11.1

**Comment by danielstjules** [comment]
Though you closed it, upgrading to node 6 should fix this :)
